const ScreenKeys = {
  RENDER_VIEW: 'RENDER_VIEW',
  ROOT: 'ROOT',
  MODAL: 'MODAL',
  HOME: 'HOME',
  BLANK: 'BLANK',

  GAME: 'GAME',
  GAME_PLAY: 'GAME/PLAY',
  GAME_WAIT: 'GAME/WAIT',

  DIALOG: 'DIALOG',
  DIALOG_GAME_EXIT: 'DIALOG_GAME_EXIT',
  DIALOG_GAME_END: 'DIALOG_GAME_END',
  DIALOG_COMING_SOON: 'DIALOG_COMING_SOON',
};

export {ScreenKeys};
