const ScreenKeys = {
  ROOT: 'ROOT',
  BLANK: 'BLANK',

  HOME_STACK: 'HomeStackScreen',
  BLANK_STACK: 'CreateCardTypeStackScreen',
  LIBRARY_STACK: 'LibraryStackScreen',

  HOME: 'HOME',
  PLAY_GAME: 'GAME/PLAY',
  WAIT_GAME: 'GAME/WAIT',

  AUTHENTICATION: 'AUTHENTICATION',
  SIGNUP_AU: 'AU/SIGNUP',
  NAME_AU: 'AU/NAME',

  LIBRARY: 'LIBRARY',
  SEARCH_LIB: 'LIB/SEARCH',
  ACTION_LIB: 'LIB/ACTION',

  CREATE_CARD: 'ACTION/CARD',
  CREATE_DECK: 'ACTION/DECK',

  BASIC_DIALOG: 'DIALOG/BASIC',
  CARD_DIALOG: 'DIALOG/CARD',
  MAIN_DIALOG: 'DIALOG/MAIN',
};

export {ScreenKeys};
