const ScreenKeys = {
  RENDER_VIEW: 'RENDER_VIEW',
  ROOT: 'ROOT',
  MODAL: 'MODAL',
  HOME: 'HOME',

  SPLASH: 'SPLASH',

  GAME: 'GAME',
  GAME_PLAY: 'GAME/PLAY',
  GAME_END: 'GAME/END',
  GAME_WAIT: 'GAME/WAIT',

  DIALOG: 'DIALOG',
  DIALOG_GAME_EXIT: 'DIALOG_GAME_EXIT',
};

export {ScreenKeys};
