const KEY = {
  RECENTLY_PLAY: '@RECENTLY_PLAY',
  SAVE_LIB: '@SAVE_LIB',
  SAVE_PIN_DECK: '@SAVE_PIN_DECK',
  DECKS_STORAGE: '@DECKS_STORAGE',
  DECK_COUNT: '@DECK_COUNT',
};
const LIMIT = {
  LIB_CARD_DECKS: 6,
  RECENTLY_CARD_DECKS: 3,
};
export {KEY, LIMIT};
