const KEY = {
  RECENTLY_CARD_DECK_ID_KEYS: '@RECENTLY_CARD_DECK_ID_KEYS',
  SAVE_LIB: '@SAVE_LIB',
  SAVE_PIN_DECK: '@SAVE_PIN_DECK',
  CARD_DECK: '@CARD_DECK',
  DECK_COUNT: '@DECK_COUNT',
};
const LIMIT = {
  LIB_CARD_DECKS: 6,
  RECENTLY_CARD_DECKS: 4,
};
export {KEY, LIMIT};
