const fontFamily = {
  roboto: 'Roboto',
  greatVibes: 'GreatVibes-Regular',
};

const Typography = {
  display: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: 0,
      fontWeight: '400',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
      fontWeight: '400',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
      fontWeight: '400',
    },
  },
  headline: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
      fontWeight: '400',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
      fontWeight: '400',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
      fontWeight: '400',
    },
  },
  heading: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
      fontWeight: '400',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 20,
      lineHeight: 26,
      letterSpacing: 0,
      fontWeight: '400',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 18,
      lineHeight: 25,
      letterSpacing: 0,
      fontWeight: '400',
    },
  },
  heading: {
    large: {
      fontSize: 24,
      fontWeight: 'normal',
      lineHeight: 32,
      letterSpacing: 0,
      fontFamily: 'Roboto',
    },
    medium: {
      fontSize: 20,
      fontWeight: 'normal',
      lineHeight: 26,
      letterSpacing: 0,
      fontFamily: 'Roboto',
    },
    small: {
      fontSize: 18,
      fontWeight: 'normal',
      lineHeight: 25,
      letterSpacing: 0.15,
      fontFamily: 'Roboto',
    },
  },
  title: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: '400',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
      fontWeight: '500',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      fontWeight: '500',
    },
  },
  label: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
      fontWeight: '500',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      fontWeight: '500',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
      fontWeight: '500',
    },
  },
  body: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
      fontWeight: '400',
    },
    medium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      fontWeight: '400',
    },
  },
  subHead: {
    large: {
      fontFamily: fontFamily?.roboto,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      fontWeight: '500',
    },
    small: {
      fontFamily: fontFamily?.roboto,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      fontWeight: '400',
    },
  },
  caption: {
    fontFamily: fontFamily?.roboto,
    fontSize: 12,
    lineHeight: 16,
    letterSpacing: 0.4,
    fontWeight: '400',
  },
  other: {
    headingLarge: {
      fontFamily: fontFamily?.roboto,
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
      fontWeight: '700',
    },
    headingMedium: {
      fontFamily: fontFamily?.roboto,
      fontSize: 18,
      lineHeight: 25,
      letterSpacing: 0.15,
      fontWeight: '500',
    },
    headingSmall: {
      fontFamily: fontFamily?.roboto,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      fontWeight: '500',
    },
    subHeadLarge: {
      fontFamily: fontFamily?.greatVibes,
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
      fontWeight: '400',
    },
    subHeadSmall: {
      fontFamily: fontFamily?.greatVibes,
      fontSize: 20,
      lineHeight: 26,
      letterSpacing: 0,
      fontWeight: '400',
    },
    caption: {
      fontFamily: fontFamily?.roboto,
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
      fontWeight: '500',
    },
  },
};

export default Typography;
