const baseStyle = {
  fontFamily: 'Roboto',
};
const Typography = {
  display: {
    large: {
      ...baseStyle,
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: 0,
      fontWeight: 400,
    },
    medium: {
      ...baseStyle,
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
      fontWeight: 400,
    },
    small: {
      ...baseStyle,
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
      fontWeight: 400,
    },
  },
  headline: {
    large: {
      ...baseStyle,
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
      fontWeight: 400,
    },
    medium: {
      ...baseStyle,
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
      fontWeight: 400,
    },
    small: {
      ...baseStyle,
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
      fontWeight: 400,
    },
  },
  heading: {
    large: {
      ...baseStyle,
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
      fontWeight: 400,
    },
    medium: {
      ...baseStyle,
      fontSize: 20,
      lineHeight: 26,
      letterSpacing: 0,
      fontWeight: 400,
    },
    small: {
      ...baseStyle,
      fontSize: 18,
      lineHeight: 25,
      letterSpacing: 0,
      fontWeight: 400,
    },
  },
  title: {
    large: {
      ...baseStyle,
      fontSize: 22,
      lineHeight: 28,
      fontWeight: 400,
    },
    medium: {
      ...baseStyle,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
      fontWeight: 500,
    },
    small: {
      ...baseStyle,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      fontWeight: 500,
    },
  },
  label: {
    large: {
      ...baseStyle,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
      fontWeight: 500,
    },
    medium: {
      ...baseStyle,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
      fontWeight: 500,
    },
    small: {
      ...baseStyle,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
      fontWeight: 500,
    },
  },
  body: {
    large: {
      ...baseStyle,
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
      fontWeight: 400,
    },
    medium: {
      ...baseStyle,
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
      fontWeight: 400,
    },
    small: {
      ...baseStyle,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      fontWeight: 400,
    },
    subHead: {
      large: {
        ...baseStyle,
        fontSize: 14,
        lineHeight: 20,
        letterSpacing: 0.1,
        fontWeight: 500,
      },
      small: {
        ...baseStyle,
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.4,
        fontWeight: 400,
      },
    },
    caption: {
      ...baseStyle,
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
      fontWeight: 400,
    },
    other: {
      headingLarge: {
        ...baseStyle,
        fontSize: 32,
        lineHeight: 40,
        letterSpacing: 0,
        fontWeight: 700,
      },
      headingMedium: {
        ...baseStyle,
        fontSize: 18,
        lineHeight: 25,
        letterSpacing: 0.15,
        fontWeight: 500,
      },
      headingSmall: {
        ...baseStyle,
        fontSize: 12,
        lineHeight: 16,
        letterSpacing: 0.4,
        fontWeight: 500,
      },
      subHeadLarge: {
        fontFamily: '',
        fontSize: 32,
        lineHeight: 40,
        letterSpacing: 0,
        fontWeight: 400,
      },
      subHeadSmall: {
        fontFamily: '',
        fontSize: 20,
        lineHeight: 26,
        letterSpacing: 0,
        fontWeight: 400,
      },
      caption: {
        ...baseStyle,
        fontSize: 11,
        lineHeight: 16,
        letterSpacing: 0.5,
        fontWeight: 500,
      },
    },
  },
};

export default Typography;
