export const FETCH_DECKS_REQUEST = 'FETCH_DECKS_REQUEST';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
export const FETCH_DECKS_ERROR = 'FETCH_DECKS_ERROR';

export const FETCH_DECKS_REQUEST_2 = 'FETCH_DECKS_REQUEST_2';
export const FETCH_DECKS_SUCCESS_2 = 'FETCH_DECKS_SUCCESS_2';
export const FETCH_DECKS_ERROR_2 = 'FETCH_DECKS_ERROR_2';
