export const FETCH_DECK_REQUEST = 'FETCH_DECK_REQUEST';
export const FETCH_DECK_SUCCESS = 'FETCH_DECK_SUCCESS';
export const FETCH_DECK_ERROR = 'FETCH_DECK_ERROR';

export const ADD_RECENTLY_KEYSTORE = 'ADD_DECK_ID';
export const GET_RECENTLY_KEYSTORE = 'GET_DECK_ID';
