export const FETCH_DECK_AND_CARDS_REQUEST = 'FETCH_DECK_AND_CARDS_REQUEST';
export const FETCH_DECK_AND_CARDS_SUCCESS = 'FETCH_DECK_AND_CARDS_SUCCESS';
export const FETCH_DECK_AND_CARDS_ERROR = 'FETCH_DECK_AND_CARDS_ERROR';
