export const ADD_RECENTLY_KEYSTORE = 'ADD_DECK_ID';
export const GET_RECENTLY_KEYSTORE = 'GET_DECK_ID';

export const ADD_LIBRARY_KEYSTORE = 'ADD_LIBRARY_KEYSTORE';
export const GET_LIBRARY_KEYSTORE = 'GET_LIBRARY_KEYSTORE';
export const REMOVE_LIBRARY_KEYSTORE = 'REMOVE_LIBRARY_KEYSTORE';
