export const FETCH_POPULAR_DECKS_REQUEST = 'FETCH_POPULAR_DECKS_REQUEST';
export const FETCH_POPULAR_DECKS_SUCCESS = 'FETCH_POPULAR_DECKS_SUCCESS';
export const FETCH_POPULAR_DECKS_ERROR = 'FETCH_POPULAR_DECKS_ERROR';
