export const FETCH_RECENTLY_DECKS_REQUEST = 'FETCH_RECENTLY_DECKS_REQUEST';
export const FETCH_RECENTLY_DECKS_SUCCESS = 'FETCH_RECENTLY_DECKS_SUCCESS';
export const FETCH_RECENTLY_DECKS_ERROR = 'FETCH_RECENTLY_DECKS_ERROR';
