export const FETCH_SUGGESTED_HASHTAG_REQUEST =
  'FETCH_SUGGESTED_HASHTAG_REQUEST';
export const FETCH_SUGGESTED_HASHTAG_SUCCESS =
  'FETCH_SUGGESTED_HASHTAG_SUCCESS';
export const FETCH_SUGGESTED_HASHTAG_ERROR = 'FETCH_SUGGESTED_HASHTAG_ERROR';
